'use client';
import { useEffect, useRef, useState } from 'react';
import { upload } from '@vercel/blob/client';
import { ArrowDownToLine, ArrowRight, Check, CheckCheck, ChevronRight, Clapperboard, Copy, ExternalLink, Film, FolderOpen, Image as ImageIcon, Layers3, Link2, LoaderCircle, LockKeyhole, Plus, Radio, RefreshCw, Settings2, Sparkles, Trash2, UploadCloud, X } from 'lucide-react';
import { buildCsv, MAX_CATALOG_PRODUCTS, type Catalog, type Product } from '@/lib/catalog';
import { captureFrame } from '@/lib/video';
import DraftManager from './draft-manager';
import { generateDefaults, inferProductType, creativeOfferUrl } from '@/lib/generate';

type Item=Product & {preview?:string;source?:string;duration?:number;frameTime?:number;status?:string};
type Notice={text:string;error?:boolean};
const blank=(name:string)=>({id:crypto.randomUUID(),name,products:[] as Item[]});
export default function Home(){
 const [ready,setReady]=useState(false),[locked,setLocked]=useState(false),[secret,setSecret]=useState(''),[local,setLocal]=useState(true),[storage,setStorage]=useState(true);
 const [catalog,setCatalog]=useState<{id:string;name:string;products:Item[];feedUrl?:string}>(()=>({id:'',name:'Meu catálogo',products:[]}));
 const [offer,setOffer]=useState(''),[brand,setBrand]=useState(''),[price,setPrice]=useState(''),[currency,setCurrency]=useState<Product['currency']>('BRL');
 const [busy,setBusy]=useState(''),[progress,setProgress]=useState(0),[notice,setNotice]=useState<Notice|null>(null),[selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState<'create'|'catalogs'>('catalogs'),[saved,setSaved]=useState<Catalog[]>([]),[dirty,setDirty]=useState(false),[drag,setDrag]=useState(false),[settings,setSettings]=useState(false),[frame,setFrame]=useState('1');
 const [creating,setCreating]=useState(false),[newName,setNewName]=useState('');
 const [productPage,setProductPage]=useState(1);
 const currentProductPage=Math.min(productPage,Math.max(1,Math.ceil(catalog.products.length/25)));
 const input=useRef<HTMLInputElement>(null);const resources=useRef<string[]>([]);
 const active=catalog.products.find(p=>p.id===selected);
 async function api(url:string,options:RequestInit={}){const response=await fetch(url,{...options,headers:{...options.headers,Authorization:`Bearer ${sessionStorage.getItem('feedstudio-key')||''}`}});const data=await response.json();if(response.status===401)setLocked(true);if(!response.ok)throw new Error(data.error||'Não foi possível concluir.');return data;}
 async function connect(key?:string){try{if(key!==undefined)sessionStorage.setItem('feedstudio-key',key);const status=await api('/api/status');setLocal(status.local);setStorage(status.storage);setLocked(false);setReady(true);setSaved(await api('/api/catalogs'));}catch(e){setReady(true);setLocked(true);if(key!==undefined)setNotice({text:(e as Error).message,error:true});}}
 useEffect(()=>{void connect();return()=>resources.current.forEach(url=>URL.revokeObjectURL(url));},[]);
 useEffect(()=>{if(!dirty)return;const listener=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[dirty]);
 function touch(){setDirty(true);}
 function patch(id:string,values:Partial<Item>){setCatalog(c=>({...c,products:c.products.map(p=>p.id===id?{...p,...values}:p)}));touch();}
 async function send(file:File){
  if(local){const form=new FormData();form.set('file',file);return (await api('/api/local-upload',{method:'POST',body:form})).url as string;}
  const ext=file.type==='image/jpeg'?'jpg':file.type==='video/quicktime'?'mov':file.type==='video/webm'?'webm':'mp4';
  const result=await upload(`media/${crypto.randomUUID()}.${ext}`,file,{access:'public',handleUploadUrl:'/api/upload',headers:{Authorization:`Bearer ${sessionStorage.getItem('feedstudio-key')||''}`},multipart:true,onUploadProgress:event=>setProgress(Math.round(event.percentage))});return result.url;
 }
 async function addFiles(files:FileList|File[]|null){
  if(!files||busy)return;
  if(!catalog.id){setNotice({text:'Crie ou selecione um catálogo antes de adicionar produtos.',error:true});return;}
  const list=Array.from(files);if(catalog.products.length+list.length>MAX_CATALOG_PRODUCTS||catalog.products.filter(p=>!p.source_product_id).length+list.length>100){setNotice({text:'Use até 100 criativos por catálogo.',error:true});return;}
  setNotice(null);let count=0;const errors:string[]=[];const added:Item[]=[];
  let defaults;try{defaults=generateDefaults(offer,currency);}catch{setNotice({text:'Cole um link de oferta válido antes de enviar os vídeos.',error:true});return;}
  const generatedBrand=brand||defaults.brand;const generatedPrice=price||defaults.price;

  for(const [index,file] of list.entries()){
   let source='';
   try{
    if(!['video/mp4','video/quicktime','video/webm'].includes(file.type)||file.size>500*1024*1024)throw new Error('Envie MP4, MOV ou WebM de até 500 MB.');
    setBusy(`Capturando frame · ${index+1}/${list.length}`);setProgress(0);
    source=URL.createObjectURL(file);resources.current.push(source);const shot=await captureFrame(source);resources.current.push(shot.preview);
    setBusy(`Enviando ${file.name} · ${index+1}/${list.length}`);
    const videoUrl=await send(file);setBusy(`Hospedando a imagem · ${index+1}/${list.length}`);const imageUrl=await send(new File([shot.blob],'frame.jpg',{type:'image/jpeg'}));
    const title=defaults.title;
    const item:Item={id:`item_${crypto.randomUUID()}`,title,description:defaults.description,product_type:defaults.product_type,brand:generatedBrand,price:generatedPrice,currency,link:creativeOfferUrl(offer),image_link:imageUrl,video_link:videoUrl,availability:'in stock',condition:'new',fileName:file.name,preview:shot.preview,source,duration:shot.duration,frameTime:shot.time};
    added.push(item);setCatalog(c=>({...c,products:[...c.products,item]}));setSelected(item.id);setFrame(shot.time.toFixed(2));touch();count++;
   }catch(e){errors.push(`${file.name}: ${(e as Error).message}`);}
  }
  if(added.length){try{setBusy('Salvando produtos no catálogo…');const next={...catalog,products:[...catalog.products,...added]};const result=await saveCatalog(next);setCatalog({...result,products:next.products});setDirty(false);}catch(e){errors.push(`Arquivos enviados, mas os produtos não foram salvos: ${(e as Error).message} Use Salvar alterações para tentar novamente.`);}}
  setBusy('');setProgress(0);if(input.current)input.current.value='';setNotice({text:errors.length?`${count} enviado(s). ${errors.join(' ')}`:`${count} produto(s) salvo(s) em ${catalog.name}, com imagem e vídeo hospedados.`,error:errors.length>0});
 }
 function applyCommon(){if(!selected)return;patch(selected,{...(brand?{brand}:{}),...(price?{price}:{}),...(offer?{link:offer}:{})});setNotice({text:'Ajustes aplicados somente ao produto selecionado. Salve as alterações para atualizar o feed.'});}
 function regenerate(){try{const defaults=generateDefaults(offer,currency);setBrand(defaults.brand);setPrice(defaults.price);if(selected)patch(selected,{...defaults});touch();setNotice({text:'Sugestões regeneradas. Os IDs, links das ofertas e das mídias foram mantidos.'});}catch{setNotice({text:'Informe um link válido para gerar os dados.',error:true});}}
 async function recapture(){if(!active)return;const time=Number(frame);if(!Number.isFinite(time)||time<0){setNotice({text:'Informe um tempo válido em segundos.',error:true});return;}setBusy('Capturando novo frame…');try{const shot=await captureFrame(active.source||active.video_link,time);resources.current.push(shot.preview);const url=await send(new File([shot.blob],'frame.jpg',{type:'image/jpeg'}));patch(active.id,{image_link:url,preview:shot.preview,frameTime:shot.time,duration:shot.duration});setFrame(shot.time.toFixed(2));setNotice({text:'Nova imagem capturada e hospedada.'});}catch(e){setNotice({text:(e as Error).message,error:true});}finally{setBusy('');}}
 async function saveCatalog(next:Catalog){buildCsv(next);const result=await api('/api/catalogs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});setSaved(rows=>[result,...rows.filter(c=>c.id!==result.id)]);return result as Catalog;}
 async function createCatalog(){if(!newName.trim()||busy)return;setBusy('Criando catálogo…');try{const result=await saveCatalog(blank(newName.trim()));selectCatalog(result);setCreating(false);setNewName('');setNotice({text:'Catálogo criado. Os próximos produtos serão salvos dentro dele.'});}catch(e){setNotice({text:(e as Error).message,error:true});}finally{setBusy('');}}
 async function publish(){setBusy('Publicando catálogo…');try{const result=await saveCatalog(catalog);setCatalog(c=>({...c,feedUrl:result.feedUrl}));setDirty(false);setNotice({text:local?'Catálogo salvo localmente. Após o deploy, publique para obter uma URL pública.':'Catálogo publicado! Copie a URL do feed para o TikTok.'});}catch(e){setNotice({text:(e as Error).name==='ZodError'?'Confira título, descrição, marca, preço e link de cada criativo.':(e as Error).message,error:true});}finally{setBusy('');}}
 async function listCatalogs(){if(busy)return;setTab('catalogs');setBusy('Carregando catálogos…');try{setSaved(await api('/api/catalogs'));}catch(e){setNotice({text:(e as Error).message,error:true});}finally{setBusy('');}}
 function newCatalog(){if(busy)return;if(dirty&&!confirm('Há alterações não salvas. Descartar e criar outro catálogo?'))return;setNewName('');setCreating(true);}
 function selectCatalog(c:Catalog){setProductPage(1);setCatalog(c);setOffer('');setBrand('');setPrice('');setCurrency(c.products[0]?.currency||'BRL');setSelected(c.products[0]?.id||null);setFrame('1');setDirty(false);setTab('create');}
 function openCatalog(c:Catalog){if(busy)return;if(dirty&&!confirm('Descartar as alterações não salvas para abrir este catálogo?'))return;selectCatalog(c);}
 async function copyUrl(url:string){try{await navigator.clipboard.writeText(url);setNotice({text:'URL do catálogo copiada.'});}catch{setNotice({text:'Selecione e copie a URL exibida no catálogo.',error:true});}}
 async function copy(){try{await navigator.clipboard.writeText(catalog.feedUrl!);setNotice({text:'URL do feed copiada.'});}catch{setNotice({text:'Selecione e copie o link do feed abaixo.',error:true});}}
 function download(){try{const url=URL.createObjectURL(new Blob([buildCsv(catalog)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`catalogo-${catalog.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setNotice({text:'Preencha todos os campos obrigatórios antes de baixar o CSV.',error:true});}}
 const complete=catalog.products.filter(p=>p.title&&p.brand&&p.description&&Number(p.price)>0&&/^https?:\/\//.test(p.link)&&p.image_link&&p.video_link).length;
 return <div className="shell">
  <aside className="sidebar"><a className="logo" href="/"><span className="logo-icon"><Layers3 size={23}/></span>feedstudio<span className="logo-period">.</span></a><div className="workspace-label">SEU WORKSPACE</div><nav><button className={tab==='create'?'nav active':'nav'} disabled={!catalog.id||!!busy} onClick={()=>setTab('create')}><Clapperboard size={19}/> Produtos <Plus size={16}/></button><button className={tab==='catalogs'?'nav active':'nav'} onClick={listCatalogs}><FolderOpen size={19}/> Meus catálogos</button></nav><div className="sidebar-bottom"><div className="integration"><span className="tiktok-mark">♪</span><div><strong>TikTok Catalog</strong><span>Exportação CSV</span></div><CheckCheck size={17}/></div><button className="nav" onClick={()=>setSettings(true)}><Settings2 size={18}/> Configuração</button><div className="profile"><span>FS</span><div><strong>Meu workspace</strong><small>{local?'Ambiente local':'Vercel + Blob'}</small></div></div></div></aside>
  <div className="main"><header className="topbar"><div>Workspace <ChevronRight size={14}/> <strong>{tab==='create'?catalog.name:'Meus catálogos'}</strong></div><span className="mode"><span/>{local?'Modo local':'Armazenamento conectado'}</span></header>
  <main className="content"><div className="page-heading"><div><div className="eyebrow">DO CRIATIVO AO CATÁLOGO</div><h1>{tab==='create'?catalog.name:'Seus catálogos, em um só lugar.'}</h1><p>{tab==='create'?'Adicione ofertas e criativos a este catálogo. Cada oferta mantém seus próprios dados.':'Crie catálogos separados, cada um com seus produtos e sua própria URL de feed.'}</p></div><span className="format-chip"><Radio size={15}/> TikTok CSV</span></div>
  {notice&&<div role="status" className={`notice ${notice.error?'error':''}`}><span>{notice.text}</span><button aria-label="Fechar aviso" onClick={()=>setNotice(null)}><X size={16}/></button></div>}
  {local&&ready&&<div className="local-note"><span>Prévia local</span> Os uploads ficam neste computador. Conecte o Blob na Vercel para gerar links públicos.</div>}
  {!storage&&<div className="notice error">Conecte um Blob Store público na Vercel para enviar os arquivos.</div>}
  {tab==='create'&&<div className="catalog-switcher"><label>Catálogo selecionado<select value={catalog.id} disabled={!!busy} onChange={e=>{const next=saved.find(c=>c.id===e.target.value);if(next)openCatalog(next);}}>{saved.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button className="secondary" disabled={!!busy} onClick={newCatalog}><Plus size={16}/> Novo catálogo</button><span>{catalog.products.length} produto(s){dirty?' · Alterações não salvas':''}</span></div>}
  {tab==='catalogs'?<section className="panel library"><div className="panel-title"><h2>Meus catálogos</h2><button className="primary small" disabled={!!busy||!ready||locked||!storage} onClick={newCatalog}><Plus size={16}/> Novo catálogo</button></div>{!saved.length?<div className="empty-library"><FolderOpen size={36}/><h3>{busy||'Crie seu primeiro catálogo.'}</h3><p>Dê um nome e depois adicione os produtos dentro dele.</p></div>:saved.map(c=><article className="catalog-card" key={c.id}><button className="catalog-open" disabled={!!busy} onClick={()=>openCatalog(c)}><span className="file-symbol"><Layers3/></span><div><strong>{c.name}</strong><small>{c.products.length} produto(s) · {c.updatedAt?new Date(c.updatedAt).toLocaleDateString('pt-BR'):''}</small></div><span className="text-button">Abrir produtos <ChevronRight size={16}/></span></button><div className="catalog-url"><input aria-label={'URL do feed de '+c.name} readOnly value={c.feedUrl||''} onFocus={e=>e.target.select()}/><button className="secondary" aria-label={'Copiar URL de '+c.name} onClick={()=>void copyUrl(c.feedUrl!)}><Copy size={16}/></button></div></article>)}</section>:<fieldset className="workspace-fields" disabled={!!busy}><div className="workspace-grid"><div className="editor-column">
   <section className="panel"><div className="panel-title"><div><span className="step">01</span><h2>Adicionar produto</h2></div><span className="muted">Preenchimento automático</span></div><div className="panel-body"><label>Link da oferta <span className="required">*</span><div className="input-icon"><Link2 size={17}/><input type="url" value={offer} onChange={e=>setOffer(e.target.value)} placeholder="https://sualoja.com/produto"/></div></label><div className="auto-frame"><Sparkles size={17}/><span>Nome, SKU, descrição, categoria, marca e preço gerados ao enviar. Moeda: <strong>{currency}</strong>.</span></div><p className="generation-note">Cada novo produto recebe um caminho exclusivo no link da oferta. Sua página precisa aceitar esses caminhos e abrir a mesma oferta.</p><p className="generation-note">Os dados e preços são sugestões, sem leitura da oferta. Você pode ajustá-los abaixo para corresponder ao produto anunciado.</p><details className="auto-settings"><summary>Ajustes do catálogo (opcional)</summary><label>Nome do catálogo<input value={catalog.name} maxLength={100} onChange={e=>{setCatalog(c=>({...c,name:e.target.value}));touch();}}/></label><div className="fields-three"><label>Marca<input value={brand} maxLength={150} onChange={e=>setBrand(e.target.value)} placeholder="Automática"/></label><label>Preço<input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value.replace(',','.'))} placeholder="Automático"/></label><label>Moeda do catálogo TikTok<select value={currency} onChange={e=>{const value=e.target.value as Product['currency'];setCurrency(value);setCatalog(c=>({...c,products:c.products.map(p=>({...p,currency:value}))}));touch();}}><option>BRL</option><option>ARS</option><option>USD</option><option>EUR</option></select></label></div><p className="generation-note">A moeda deve ser igual à do catálogo TikTok. Trocar a moeda não converte o preço.</p><div className="field-foot"><button className="secondary" disabled={!!busy||!offer} onClick={regenerate}><Sparkles size={14}/> Regenerar sugestões</button>{catalog.products.length>0&&<button className="text-button" disabled={!!busy} onClick={applyCommon}>Aplicar ao produto selecionado <ArrowRight size={14}/></button>}</div></details></div></section>
   <section className="panel"><div className="panel-title"><div><span className="step">02</span><h2>Produtos deste catálogo</h2><span className="count">{catalog.products.length}</span></div><span className="muted">Um item por vídeo</span></div><div className="panel-body"><input ref={input} className="sr-only" type="file" accept="video/mp4,video/quicktime,video/webm" multiple onChange={e=>void addFiles(e.target.files)}/><button disabled={!!busy||!storage||!ready||!catalog.id} className={`dropzone ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void addFiles(e.dataTransfer.files);}} onClick={()=>input.current?.click()}><span className="upload-icon">{busy?<LoaderCircle className="spin" size={25}/>:<UploadCloud size={27}/>}</span><strong>{busy||'Arraste seus vídeos para cá'}</strong><span>{busy?(progress>0?`${progress}% enviado`:'Só um instante…'):<>ou <b>escolha os arquivos</b> no seu computador</>}</span><small>MP4, MOV ou WebM · até 500 MB por vídeo</small></button><div className="auto-frame"><ImageIcon size={17}/><span>Um frame do vídeo vira a imagem do produto, automaticamente.</span><span className="auto-badge">AUTO</span></div>
    {catalog.products.length>0&&<div className="video-list">{catalog.products.slice((currentProductPage-1)*25,currentProductPage*25).map(p=><div className={`video-row ${selected===p.id?'selected':''}`} key={p.id}><button className="video-select" onClick={()=>{setSelected(p.id);setFrame(String(p.frameTime??1));}}><img src={p.preview||p.image_link} alt={`Frame de ${p.title}`}/><span><strong>{p.title}</strong><small>{p.fileName}</small><em><Check size={12}/> Vídeo + imagem hospedados</em></span></button><button className="icon-button" disabled={!!busy} aria-label={`Remover ${p.title}`} onClick={()=>{setCatalog(c=>({...c,products:c.products.filter(i=>i.id!==p.id)}));if(selected===p.id)setSelected(null);touch();}}><Trash2 size={16}/></button></div>)}</div>}
   {catalog.products.length>25&&<div className="draft-pagination"><button className="secondary" disabled={currentProductPage<=1} onClick={()=>setProductPage(currentProductPage-1)}>Anterior</button><span>Página {currentProductPage} de {Math.ceil(catalog.products.length/25)}</span><button className="secondary" disabled={currentProductPage*25>=catalog.products.length} onClick={()=>setProductPage(currentProductPage+1)}>Próxima</button></div>}
   </div></section>
   <DraftManager key={catalog.id} catalogId={catalog.id} productCount={catalog.products.length} disabled={dirty||!!busy} onBusyChange={value=>setBusy(value?"Publicando rascunhos…":"")} onPublished={async()=>{const rows=await api("/api/catalogs");setSaved(rows);const updated=rows.find((c:Catalog)=>c.id===catalog.id);if(updated)selectCatalog(updated);}}/>
   {active&&<details className="panel individual-editor"><summary>Ajustar dados do criativo (opcional)</summary><div className="panel-title"><div><span className="step">03</span><h2>Revisar criativo</h2></div><span className="muted">Edição individual</span></div><div className="panel-body"><label>Nome do produto<input maxLength={500} value={active.title} onChange={e=>patch(active.id,{title:e.target.value})}/></label><label>Categoria do produto<input maxLength={750} value={active.product_type??inferProductType(active.title+" "+active.link)} onChange={e=>patch(active.id,{product_type:e.target.value})}/></label><label>Descrição<textarea rows={3} maxLength={10000} value={active.description} onChange={e=>patch(active.id,{description:e.target.value})}/></label><div className="fields-three"><label>Marca<input value={active.brand} maxLength={150} onChange={e=>patch(active.id,{brand:e.target.value})}/></label><label>Preço<input inputMode="decimal" value={active.price} onChange={e=>patch(active.id,{price:e.target.value.replace(',','.')})}/></label><label>Moeda<select value={active.currency} onChange={e=>patch(active.id,{currency:e.target.value as Product['currency']})}><option>BRL</option><option>ARS</option><option>USD</option><option>EUR</option></select></label></div><label>Link da oferta<input type="url" value={active.link} onChange={e=>patch(active.id,{link:e.target.value})}/></label><div className="fields-two"><label>Disponibilidade<select value={active.availability} onChange={e=>patch(active.id,{availability:e.target.value as Product['availability']})}><option value="in stock">Em estoque</option><option value="out of stock">Sem estoque</option><option value="preorder">Pré-venda</option><option value="available">Disponível</option><option value="discontinued">Descontinuado</option></select></label><label>Condição<select value={active.condition} onChange={e=>patch(active.id,{condition:e.target.value as Product['condition']})}><option value="new">Novo</option><option value="used">Usado</option><option value="refurbished">Recondicionado</option></select></label></div><div className="frame-picker"><div><label htmlFor="frame-time">Momento da imagem (segundos)</label><div className="frame-controls"><input id="frame-time" type="number" min="0" step="0.1" max={active.duration} value={frame} onChange={e=>setFrame(e.target.value)}/><button className="secondary" disabled={!!busy} onClick={recapture}><RefreshCw size={15}/> Capturar outro frame</button></div></div></div><details><summary>Links e identificação</summary><p className="mono">{active.id}</p><a href={active.image_link} target="_blank" rel="noreferrer">Abrir imagem JPG <ExternalLink size={13}/></a><a href={active.video_link} target="_blank" rel="noreferrer">Abrir vídeo <ExternalLink size={13}/></a></details></div></details>}
  </div><aside className="summary-column"><section className="preview-card"><div className="preview-heading"><span>PRÉVIA DO PRODUTO</span><Film size={16}/></div><div className={`product-preview ${active?'has-image':''}`}>{active?<><img src={active.preview||active.image_link} alt={`Imagem do catálogo: ${active.title}`}/><span className="frame-tag"><ImageIcon size={12}/> Frame do criativo</span></>:<div className="preview-empty"><span><Clapperboard size={34}/></span><strong>Seu criativo ganha vida aqui</strong><p>A imagem será capturada<br/>direto do seu vídeo.</p></div>}</div><div className="preview-description"><small>{active?.brand||'SUA MARCA'}</small><strong>{active?.title||'Nome do produto'}</strong><div>{active?.price?new Intl.NumberFormat('pt-BR',{style:'currency',currency:active.currency}).format(Number(active.price)||0):'R$ —'}<span>{active?'Prévia do item':'Aguardando criativo'}</span></div></div></section>
  <section className="panel publish-panel"><h2>Pronto para conectar.</h2><p>Seu catálogo em uma URL, sempre no mesmo endereço.</p><div className="summary-line"><span>Criativos enviados</span><strong>{catalog.products.length.toString().padStart(2,'0')}</strong></div><div className="summary-line"><span>Imagens capturadas</span><strong>{catalog.products.length.toString().padStart(2,'0')}</strong></div><div className="summary-line"><span>Itens preenchidos</span><strong>{complete} / {catalog.products.length}</strong></div><div className="summary-line"><span>Formato de saída</span><span className="xml-tag">CSV</span></div><p className="generation-note">Preço e marca gerados automaticamente. Ajustes disponíveis antes de publicar.</p><button className="primary publish" onClick={publish} disabled={!!busy||!catalog.id||complete!==catalog.products.length}>{busy?<LoaderCircle size={17} className="spin"/>:<Radio size={17}/>} {dirty?'Salvar alterações':'Atualizar catálogo'} <ArrowRight size={17}/></button><button className="download" onClick={download} disabled={!catalog.products.length||!!busy}><ArrowDownToLine size={15}/> Baixar CSV</button>{catalog.feedUrl?.endsWith(".xml")&&<p className="generation-note">Clique em Atualizar catálogo para gerar a nova URL CSV.</p>}{catalog.feedUrl&&<div className="feed-result"><strong><CheckCheck size={16}/>{dirty?'Há alterações não publicadas':local?'Feed local gerado':'Feed publicado'}</strong><label>URL do feed<input readOnly value={catalog.feedUrl} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={copy}><Copy size={14}/> Copiar URL</button></div>}</section><div className="tip"><span>↳</span><p>No TikTok Catalog Manager, cole a URL em <strong>URL do feed</strong> e escolha a frequência de atualização.</p></div></aside></div></fieldset>}
  <footer><span>feedstudio · Feito para simplificar seu catálogo.</span><span>Seus vídeos. Seu feed.</span></footer></main></div>
  {creating&&<div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="Novo catálogo" onSubmit={e=>{e.preventDefault();void createCatalog();}}><button className="modal-close icon-button" type="button" disabled={!!busy} aria-label="Fechar criação" onClick={()=>setCreating(false)}><X/></button><h2>Novo catálogo</h2><p>Cada catálogo tem seus próprios produtos e uma URL de feed exclusiva.</p><label>Nome do novo catálogo<input autoFocus required maxLength={100} disabled={!!busy} value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Ex.: Cozinha, Moda, Campanha setembro"/></label><button className="primary" type="submit" disabled={!!busy||!newName.trim()}>{busy?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>} Criar catálogo</button>{notice?.error&&<p role="alert" className="login-error">{notice.text}</p>}</form></div>}
  {locked&&<div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();void connect(secret);}}><span className="modal-icon"><LockKeyhole/></span><h2>Entre no seu workspace</h2><p>Use a chave definida em ADMIN_SECRET no projeto Vercel.</p><label>Chave de acesso<input type="password" autoComplete="current-password" required value={secret} onChange={e=>setSecret(e.target.value)}/></label><button className="primary" type="submit">Entrar <ArrowRight size={16}/></button>{notice?.error&&<p role="alert" className="login-error">{notice.text}</p>}</form></div>}
  {settings&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="Configuração"><button className="modal-close icon-button" aria-label="Fechar configuração" onClick={()=>setSettings(false)}><X/></button><h2>Conectar à Vercel</h2><p>O painel e as funções rodam na Vercel. Vídeos, imagens e feeds ficam no Vercel Blob público.</p><ol><li>Importe este projeto na Vercel.</li><li>Em Storage, crie um Blob Store <strong>público</strong> conectado ao projeto.</li><li>Defina <code>ADMIN_SECRET</code> com pelo menos 32 caracteres e faça o deploy.</li><li>Entre no painel, envie os criativos e publique o catálogo.</li></ol><p>Os links das mídias e dos feeds são públicos. O armazenamento e o tráfego seguem o plano da sua conta Vercel.</p><button className="secondary" onClick={()=>{sessionStorage.removeItem('feedstudio-key');setSettings(false);setLocked(true);}}>Sair do workspace</button></div></div>}
 </div>;
}
